version: "3"
services:
  guben-strapi:
    container_name: guben-strapi
#    build: .
    image: ghcr.io/agriculturedev/guben-cockpit-strapi-api:prod
    restart: unless-stopped
    env_file: stack.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: guben-strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/config
      - ./src:/opt/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/.env
      - ./public:/opt/public
    ports:
      - "1337:1337"
    networks:
      - strapi
      - websites
    depends_on:
      - guben-strapi-db

  guben-strapi-db:
    container_name: guben-strapiDB
    restart: unless-stopped
    env_file: stack.env
    image: ghcr.io/agriculturedev/guben-cockpit-strapi-db:prod
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
  websites:
    name: websites
    driver: bridge
