// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(GubenDbContext))]
    [Migration("20250923155329_Create_MasterportalLink_Table")]
    partial class Create_MasterportalLink_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Guben")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Booking.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("ForPublicUse")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Booking", "Guben");
                });

            modelBuilder.Entity("Domain.Category.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category", "Guben");
                });

            modelBuilder.Entity("Domain.DashboardTab.DashboardTab", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("MapUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("DashboardTab", "Guben");
                });

            modelBuilder.Entity("Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LocationId");

                    b.HasIndex("EventId", "TerminId");

                    b.ToTable("Event", "Guben");
                });

            modelBuilder.Entity("Domain.FooterItems.FooterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FooterItem", "Guben");
                });

            modelBuilder.Entity("Domain.GeoDataSource.GeoDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GeoDataSource", "Guben");
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Location", "Guben");
                });

            modelBuilder.Entity("Domain.MasterportalLinks.MasterportalLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("folder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<string>("WfsFeatureNs")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("wfs_feature_ns");

                    b.Property<string>("WfsFeatureType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("wfs_feature_type");

                    b.Property<string>("WfsVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("wfs_version");

                    b.Property<string>("WmsFeatureCount")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("wms_feature_count");

                    b.Property<string>("WmsFormat")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("wms_format");

                    b.Property<string>("WmsGfiAttributes")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("wms_gfi_attributes");

                    b.Property<string>("WmsGfiTheme")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("wms_gfi_theme");

                    b.Property<string>("WmsLayerAttribution")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("wms_layer_attribution");

                    b.Property<string>("WmsLayers")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("wms_layers");

                    b.Property<string>("WmsLegendUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("wms_legend_url");

                    b.Property<string>("WmsMaxScale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wms_max_scale");

                    b.Property<string>("WmsMinScale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wms_min_scale");

                    b.Property<string>("WmsSupported")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wms_supported");

                    b.Property<int?>("WmsTileSize")
                        .HasColumnType("integer")
                        .HasColumnName("wms_tile_size");

                    b.Property<int?>("WmsTransparency")
                        .HasColumnType("integer")
                        .HasColumnName("wms_transparency");

                    b.Property<bool?>("WmsTransparent")
                        .HasColumnType("boolean")
                        .HasColumnName("wms_transparent");

                    b.Property<string>("WmsVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("wms_version");

                    b.Property<bool?>("WmsVisibility")
                        .HasColumnType("boolean")
                        .HasColumnName("wms_visibility");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_masterportal_links_created_at");

                    b.HasIndex("Folder")
                        .HasDatabaseName("ix_masterportal_links_folder");

                    b.HasIndex("Status", "Type")
                        .HasDatabaseName("ix_masterportal_links_status_type");

                    b.ToTable("MasterportalLink", "Guben");
                });

            modelBuilder.Entity("Domain.Pages.Page", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Page", "Guben");
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageCaption")
                        .HasColumnType("text");

                    b.Property<string>("ImageCredits")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Project", "Guben");
                });

            modelBuilder.Entity("Domain.Topic.DataSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicId")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("DataSource", "Guben");
                });

            modelBuilder.Entity("Domain.Topic.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DataSourceId")
                        .HasColumnType("text");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("Source", "Guben");
                });

            modelBuilder.Entity("Domain.Topic.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topic", "Guben");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User", "Guben");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "system@example.com",
                            FirstName = "System",
                            KeycloakId = "system",
                            LastName = "User"
                        });
                });

            modelBuilder.Entity("EventCategory", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "EventsId");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("EventsId");

                    b.ToTable("EventCategory", "Guben");
                });

            modelBuilder.Entity("Domain.DashboardTab.DashboardTab", b =>
                {
                    b.OwnsMany("Domain.DashboardTab.InformationCard", "InformationCards", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DashboardTabId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Translations")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.HasKey("Id");

                            b1.HasIndex("DashboardTabId");

                            b1.ToTable("InformationCard", "Guben");

                            b1.WithOwner()
                                .HasForeignKey("DashboardTabId");

                            b1.OwnsOne("Domain.DashboardTab.Button", "Button", b2 =>
                                {
                                    b2.Property<Guid>("InformationCardId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("OpenInNewTab")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Translations")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("InformationCardId");

                                    b2.ToTable("InformationCard", "Guben");

                                    b2.WithOwner()
                                        .HasForeignKey("InformationCardId");
                                });

                            b1.Navigation("Button");
                        });

                    b.Navigation("InformationCards");
                });

            modelBuilder.Entity("Domain.Events.Event", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Locations.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Events.EventImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OriginalUrl")
                                .HasColumnType("text");

                            b1.Property<int?>("Height")
                                .HasColumnType("integer");

                            b1.Property<string>("PreviewUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ThumbnailUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("EventId", "OriginalUrl");

                            b1.ToTable("EventImages", "Guben");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsMany("Domain.Urls.Url", "Urls", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EventId", "Id");

                            b1.ToTable("Url", "Guben");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Images");

                    b.Navigation("Location");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Topic.DataSource", b =>
                {
                    b.HasOne("Domain.Topic.Topic", null)
                        .WithMany("DataSources")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("Domain.Topic.Source", b =>
                {
                    b.HasOne("Domain.Topic.DataSource", null)
                        .WithMany("Sources")
                        .HasForeignKey("DataSourceId");
                });

            modelBuilder.Entity("EventCategory", b =>
                {
                    b.HasOne("Domain.Category.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Domain.Topic.DataSource", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Domain.Topic.Topic", b =>
                {
                    b.Navigation("DataSources");
                });
#pragma warning restore 612, 618
        }
    }
}
