/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type CategoryResponse = {
  name?: string;
  /**
   * @format uuid
   */
  id: string;
};

export type CoordinatesResponse = {
  /**
   * @format double
   */
  latitude?: number;
  /**
   * @format double
   */
  longitude?: number;
} | null;

export type CreateUserQuery = {
  keycloakId: string;
};

export type CreateUserResponse = {
  /**
   * @format uuid
   */
  userId: string;
};

export type EventResponse = {
  /**
   * @format int32
   */
  id: number;
  title: string;
  description: string;
  /**
   * @format date-time
   */
  startDate: string;
  /**
   * @format date-time
   */
  endDate: string;
  location: LocationResponse;
  coordinates?: CoordinatesResponse;
  urls: UrlResponse[];
  categories: CategoryResponse[];
};

export type GetAllCategoriesResponse = {
  categories: CategoryResponse[];
};

export type GetAllEventsResponse = {
  events: EventResponse[];
};

export type GetAllLocationsResponse = {
  locations: LocationResponse[];
};

export type GetAllProjectsResponse = {
  projects: ProjectResponse[];
};

export type GetAllUsersResponse = {
  users: UserResponse[];
};

export type GetUserResponse = {
  keycloakId: string;
  /**
   * @format uuid
   */
  id: string;
};

export type LocationResponse = {
  name: string;
  city?: string | null;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type ProjectResponse = {
  title?: string;
  description?: string | null;
  fullText?: string | null;
  imageCaption?: string | null;
  imageUrl?: string | null;
  imageCredits?: string | null;
};

export type UrlResponse = {
  link?: string;
  description?: string;
};

export type UserResponse = {
  keycloakId: string;
  /**
   * @format uuid
   */
  id: string;
};
