name: Trigger Portainer Webhook on dev push

on:
  push:
    branches:
      - dev

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Webhook
        run: |
          curl -X POST "https://portainer.hagenfaber.dev/api/stacks/webhooks/3306ae6b-3937-4e75-88d3-a8d3ec5fb2e8"
